/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package korisnikGUI;

import entities.Documentrequest;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.jms.JMSContext;
import javax.jms.JMSProducer;
import javax.jms.TextMessage;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import main.Main;
import main.RegionalniCentar;
import main.ServisAplikacija;

/**
 *
 * @author aca19
 */
public class GUI extends javax.swing.JFrame {

    private static GUI guiReference = null;
    //Konstruktor GUI-a
    private GUI() {
        super("Forma");
        initComponents();
        additionalInit();
        setVisible(true);
    }
    
    public static GUI getReferenceGUI(){
        if(guiReference == null){
            guiReference = new GUI();
        }
        return guiReference;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        marriedGroup = new javax.swing.ButtonGroup();
        messageDialog = new javax.swing.JDialog();
        messageLabel = new javax.swing.JLabel();
        requestStatusDialog = new javax.swing.JDialog();
        HTTPRequestIdLabel = new javax.swing.JLabel();
        HTTPRequestIdTextField = new javax.swing.JTextField();
        requestStatusLabel = new javax.swing.JLabel();
        currentRequestStatusLabel = new javax.swing.JLabel();
        deliverButton = new javax.swing.JButton();
        jPanelPersonal = new javax.swing.JPanel();
        jmbgLabel = new javax.swing.JLabel();
        jmbgTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        DateOfBirthLabel = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        slashLabel1 = new javax.swing.JLabel();
        monthTextField = new javax.swing.JTextField();
        slashLabel2 = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        dateForm = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        separator2 = new javax.swing.JSeparator();
        nationalityLabel = new javax.swing.JLabel();
        professionLabel = new javax.swing.JLabel();
        nationalityTextField = new javax.swing.JTextField();
        professionTextField = new javax.swing.JTextField();
        marriedRadioButton = new javax.swing.JRadioButton();
        notMarriedRadioButton = new javax.swing.JRadioButton();
        divorcedRadioButton = new javax.swing.JRadioButton();
        widowedRadioButton = new javax.swing.JRadioButton();
        residenceLabel1 = new javax.swing.JLabel();
        residenceLabel2 = new javax.swing.JLabel();
        residenceLabel3 = new javax.swing.JLabel();
        residenceTextField1 = new javax.swing.JTextField();
        residenceTextField2 = new javax.swing.JTextField();
        residenceTextField3 = new javax.swing.JTextField();
        jPanelParent = new javax.swing.JPanel();
        fatherLabel = new javax.swing.JLabel();
        fatherLastNameLabel = new javax.swing.JLabel();
        motherLabel = new javax.swing.JLabel();
        mothreLastNameLabel = new javax.swing.JLabel();
        fatherFirstNameTextFiled = new javax.swing.JTextField();
        fatherLastNameTextField = new javax.swing.JTextField();
        motherFirstNameTextField = new javax.swing.JTextField();
        motherLastNameTextField = new javax.swing.JTextField();
        fatherFirstNameLabel = new javax.swing.JLabel();
        motherFirstNameLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        saveRequestButton = new javax.swing.JButton();
        requestStatusButton = new javax.swing.JButton();

        messageDialog.setMinimumSize(new java.awt.Dimension(400, 100));
        messageDialog.setResizable(false);

        messageLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        messageLabel.setText("ERROR :: Some fields are empty!");
        messageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout messageDialogLayout = new javax.swing.GroupLayout(messageDialog.getContentPane());
        messageDialog.getContentPane().setLayout(messageDialogLayout);
        messageDialogLayout.setHorizontalGroup(
            messageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(messageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(messageDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(messageLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        messageDialogLayout.setVerticalGroup(
            messageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(messageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(messageDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(messageLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        requestStatusDialog.setMinimumSize(new java.awt.Dimension(420, 120));
        requestStatusDialog.setPreferredSize(new java.awt.Dimension(420, 120));

        HTTPRequestIdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HTTPRequestIdLabel.setText("Input RequestID");

        requestStatusLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        requestStatusLabel.setText("Request Status: ");

        currentRequestStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        deliverButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deliverButton.setText("Deliver");

        javax.swing.GroupLayout requestStatusDialogLayout = new javax.swing.GroupLayout(requestStatusDialog.getContentPane());
        requestStatusDialog.getContentPane().setLayout(requestStatusDialogLayout);
        requestStatusDialogLayout.setHorizontalGroup(
            requestStatusDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestStatusDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(requestStatusDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestStatusDialogLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(currentRequestStatusLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(requestStatusDialogLayout.createSequentialGroup()
                        .addGroup(requestStatusDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(requestStatusDialogLayout.createSequentialGroup()
                                .addComponent(HTTPRequestIdLabel)
                                .addGap(18, 18, 18)
                                .addComponent(HTTPRequestIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(requestStatusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(deliverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        requestStatusDialogLayout.setVerticalGroup(
            requestStatusDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestStatusDialogLayout.createSequentialGroup()
                .addGroup(requestStatusDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, requestStatusDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deliverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, requestStatusDialogLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(currentRequestStatusLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, requestStatusDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(requestStatusDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HTTPRequestIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HTTPRequestIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(requestStatusLabel)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPersonal.setBackground(new java.awt.Color(102, 255, 178));
        jPanelPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Personal"));
        jPanelPersonal.setPreferredSize(new java.awt.Dimension(680, 300));

        jmbgLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jmbgLabel.setText("ID");

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        firstNameLabel.setText("First Name");

        firstNameTextField.setToolTipText("");
        firstNameTextField.setName(""); // NOI18N

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lastNameLabel.setText("Last Name");

        DateOfBirthLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateOfBirthLabel.setText("Date of Birth");

        slashLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        slashLabel1.setText("/");

        slashLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        slashLabel2.setText("/");

        genderGroup.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maleRadioButton.setText("Male");

        genderGroup.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        femaleRadioButton.setText("Female");

        dateForm.setForeground(new java.awt.Color(153, 153, 153));
        dateForm.setText("(dd/mm/yyyy)");

        nationalityLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nationalityLabel.setText("Nationality");

        professionLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        professionLabel.setText("Profession");

        marriedGroup.add(marriedRadioButton);
        marriedRadioButton.setText("Married");

        marriedGroup.add(notMarriedRadioButton);
        notMarriedRadioButton.setText("Not Married");

        marriedGroup.add(divorcedRadioButton);
        divorcedRadioButton.setText("Divorced");

        marriedGroup.add(widowedRadioButton);
        widowedRadioButton.setText("Widowed");

        residenceLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        residenceLabel1.setText("Township of residence");

        residenceLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        residenceLabel2.setText("Address of residence");

        residenceLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        residenceLabel3.setText("Address number of residence");

        javax.swing.GroupLayout jPanelPersonalLayout = new javax.swing.GroupLayout(jPanelPersonal);
        jPanelPersonal.setLayout(jPanelPersonalLayout);
        jPanelPersonalLayout.setHorizontalGroup(
            jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(separator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(nationalityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nationalityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(professionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(professionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(marriedRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(divorcedRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(notMarriedRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(widowedRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jmbgLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                .addComponent(jmbgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(lastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(DateOfBirthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateForm)
                                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                        .addComponent(slashLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(slashLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(maleRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(femaleRadioButton))))))
                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(residenceLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(residenceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPersonalLayout.createSequentialGroup()
                                .addComponent(residenceLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residenceTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                                .addComponent(residenceLabel2)
                                .addGap(7, 7, 7)
                                .addComponent(residenceTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPersonalLayout.setVerticalGroup(
            jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jmbgLabel)
                        .addComponent(jmbgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstNameLabel)
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNameLabel)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton)
                    .addComponent(slashLabel2)
                    .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slashLabel1)
                    .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateOfBirthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nationalityLabel)
                            .addComponent(professionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nationalityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(professionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPersonalLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marriedRadioButton)
                            .addComponent(notMarriedRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(divorcedRadioButton)
                            .addComponent(widowedRadioButton))))
                .addGap(18, 18, 18)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(residenceLabel1)
                    .addComponent(residenceLabel2)
                    .addComponent(residenceTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(residenceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(residenceTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(residenceLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        firstNameLabel.getAccessibleContext().setAccessibleName("");

        jPanelParent.setBackground(new java.awt.Color(102, 255, 178));
        jPanelParent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Parents"));
        jPanelParent.setPreferredSize(new java.awt.Dimension(0, 100));

        fatherLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fatherLabel.setText("Father");

        fatherLastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fatherLastNameLabel.setText("Last Name");

        motherLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        motherLabel.setText("Mother");

        mothreLastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mothreLastNameLabel.setText("Last Name");

        fatherFirstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fatherFirstNameLabel.setText("First Name");

        motherFirstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        motherFirstNameLabel.setText("First Name");

        javax.swing.GroupLayout jPanelParentLayout = new javax.swing.GroupLayout(jPanelParent);
        jPanelParent.setLayout(jPanelParentLayout);
        jPanelParentLayout.setHorizontalGroup(
            jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motherLabel)
                    .addGroup(jPanelParentLayout.createSequentialGroup()
                        .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fatherLabel)
                            .addGroup(jPanelParentLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(motherFirstNameLabel)
                                    .addComponent(fatherFirstNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fatherFirstNameTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(motherFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelParentLayout.createSequentialGroup()
                                .addComponent(mothreLastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(motherLastNameTextField))
                            .addGroup(jPanelParentLayout.createSequentialGroup()
                                .addComponent(fatherLastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fatherLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelParentLayout.setVerticalGroup(
            jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fatherLabel)
                .addGap(1, 1, 1)
                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatherFirstNameLabel)
                    .addComponent(fatherFirstNameTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherLastNameLabel)
                    .addComponent(fatherLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParentLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(motherLabel))
                    .addGroup(jPanelParentLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(motherFirstNameLabel)
                            .addComponent(motherFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mothreLastNameLabel)
                            .addComponent(motherLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        buttonPanel.setBackground(new java.awt.Color(102, 255, 178));
        buttonPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        saveRequestButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveRequestButton.setText("Save Request");

        requestStatusButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        requestStatusButton.setText("Request Status");

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(requestStatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(requestStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addComponent(jPanelParent, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanelPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void additionalInit(){
        this.setLocationRelativeTo(null);
        
        //Dodavanje u listu
        textFieldList = new ArrayList<JTextField>();
        textFieldList.add(jmbgTextField);
        textFieldList.add(firstNameTextField);
        textFieldList.add(lastNameTextField);
        textFieldList.add(dayTextField);
        textFieldList.add(monthTextField);
        textFieldList.add(yearTextField);
        textFieldList.add(nationalityTextField);
        textFieldList.add(professionTextField);
        textFieldList.add(residenceTextField1);
        textFieldList.add(residenceTextField2);
        textFieldList.add(residenceTextField3);
        textFieldList.add(fatherFirstNameTextFiled);
        textFieldList.add(fatherLastNameTextField);
        textFieldList.add(motherFirstNameTextField);
        textFieldList.add(motherLastNameTextField);
        
        //Setting RadioButton ActionCommand
        maleRadioButton.setActionCommand("Male");
        femaleRadioButton.setActionCommand("Female");
        marriedRadioButton.setActionCommand("Married");
        divorcedRadioButton.setActionCommand("Divorced");
        widowedRadioButton.setActionCommand("Widowed");
        notMarriedRadioButton.setActionCommand("Not Married");
        
        //MsgDialog Setup
        messageDialog.setModal(true);
        messageDialog.setLocationRelativeTo(null);
        
        //Adding window closing listener
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e){
                System.out.println("MainFrame closing!");
                ServisAplikacija.getReferenceSA().stopServisApplication();
            }
        });
        
        //Setting RequestStatsuDialog
        requestStatusDialog.setLocationRelativeTo(null);
        deliverButton.setEnabled(false);
        
        //Adding sendRequsteButtonListener
        saveRequestButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ArrayList<String> textFieldData = getTextFieldsData();
                ArrayList<String> radioButtonData = getRadioButtonData();
                
                //Check if feild is empty
                boolean isEmpty = false;
                for(String s : textFieldData)
                    if(s.isEmpty())
                        isEmpty = true;
                for(String s : radioButtonData)
                    if(s == "")
                        isEmpty = true;
                
                if(!isEmpty){
                    RegionalniCentar rc = RegionalniCentar.getReferenceRC();
                    rc.makeNewRequest(textFieldData, radioButtonData);
                }else{
                    System.out.println("---Nisu sva polja popunjena!---");
                    setMsg("ERROR :: Some fields are empty!");
                }
                
            }
        });
        
        //Adding requestStatusButton
        requestStatusButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                requestStatusDialog.setVisible(true);
            }
        });
        
        //Adding deliverButtonListener
        deliverButton.addActionListener((ActionEvent e) -> {
            RegionalniCentar.getReferenceRC().updateStatus(RegionalniCentar.getReferenceRC().getIdFromRequestId(HTTPRequestIdTextField.getText()), "Urucen");
            deliverButton.setEnabled(false);
        });
        
        /*HTTPRequestIdTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                System.out.println(HTTPRequestIdTextField.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                System.out.println(HTTPRequestIdTextField.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                System.out.println(HTTPRequestIdTextField.getText());
            }
        });*/
    }
    
    private ArrayList<String> getTextFieldsData(){
        ArrayList<String> stringList = new ArrayList<>();
        String date = "";
        
        for(int i=0; i<textFieldList.size(); i++){
            if(i == 5){
                date = textFieldList.get(i).getText() + "-" + textFieldList.get(i-1).getText() + "-" + textFieldList.get(i-2).getText() + date;
                stringList.add(date);
            }
            else if(i != 3 && i != 4)
                stringList.add(textFieldList.get(i).getText());    
        }
        return stringList;
    }
    
    private ArrayList<String> getRadioButtonData(){
        ArrayList<String> stringList = new ArrayList<>();
        try{
            stringList.add(genderGroup.getSelection().getActionCommand());
            stringList.add(marriedGroup.getSelection().getActionCommand());
        }catch(NullPointerException e){
            if(stringList.size() == 0){
                stringList.add("");
            }
            stringList.add("");
        }
        return stringList;
    }
    
    private void sendHTTPTextFieldData(){
        JMSContext context = Main.conncetionFactory.createContext();
        JMSProducer producer = context.createProducer();
        TextMessage textMsg = context.createTextMessage(HTTPRequestIdTextField.getText());
        producer.send(Main.sendQueue, textMsg);
    }
    
    public void setMsg(String errorMsg){
        messageLabel.setText(errorMsg);
        messageDialog.setVisible(true);
    }
    
    public String getHTTPRequestID(){
        return HTTPRequestIdTextField.getText();
    }
    
    public JButton getDeliverButton(){
        return deliverButton;
    }
    
    public void setStatusLabelText(String txt){
        currentRequestStatusLabel.setText(txt);
    }
    

    //msm da ovaj main ne treba da postoji
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
  

    //My Variables declaration--------------------------------------------------
    private ArrayList<JTextField> textFieldList;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateOfBirthLabel;
    private javax.swing.JLabel HTTPRequestIdLabel;
    private javax.swing.JTextField HTTPRequestIdTextField;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel currentRequestStatusLabel;
    private javax.swing.JLabel dateForm;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JButton deliverButton;
    private javax.swing.JRadioButton divorcedRadioButton;
    private javax.swing.JLabel fatherFirstNameLabel;
    private javax.swing.JTextField fatherFirstNameTextFiled;
    private javax.swing.JLabel fatherLabel;
    private javax.swing.JLabel fatherLastNameLabel;
    private javax.swing.JTextField fatherLastNameTextField;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JPanel jPanelParent;
    private javax.swing.JPanel jPanelPersonal;
    private javax.swing.JLabel jmbgLabel;
    private javax.swing.JTextField jmbgTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.ButtonGroup marriedGroup;
    private javax.swing.JRadioButton marriedRadioButton;
    private javax.swing.JDialog messageDialog;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel motherFirstNameLabel;
    private javax.swing.JTextField motherFirstNameTextField;
    private javax.swing.JLabel motherLabel;
    private javax.swing.JTextField motherLastNameTextField;
    private javax.swing.JLabel mothreLastNameLabel;
    private javax.swing.JLabel nationalityLabel;
    private javax.swing.JTextField nationalityTextField;
    private javax.swing.JRadioButton notMarriedRadioButton;
    private javax.swing.JLabel professionLabel;
    private javax.swing.JTextField professionTextField;
    private javax.swing.JButton requestStatusButton;
    private javax.swing.JDialog requestStatusDialog;
    private javax.swing.JLabel requestStatusLabel;
    private javax.swing.JLabel residenceLabel1;
    private javax.swing.JLabel residenceLabel2;
    private javax.swing.JLabel residenceLabel3;
    private javax.swing.JTextField residenceTextField1;
    private javax.swing.JTextField residenceTextField2;
    private javax.swing.JTextField residenceTextField3;
    private javax.swing.JButton saveRequestButton;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JLabel slashLabel1;
    private javax.swing.JLabel slashLabel2;
    private javax.swing.JRadioButton widowedRadioButton;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
